name: Build Docker

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: mlkit:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
